apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce  # Mode akses yang diizinkan (bisa juga ReadWriteOnce atau ReadOnlyMany)
  persistentVolumeReclaimPolicy: Retain  # Kebijakan penghapusan data setelah PVC dihapus (Retain, Recycle, Delete)
  storageClassName: standard
  nfs:
    server: 10.0.62.101
    path: /data/storage-kubernetes
